### ISSUE TITLE
I can't write on file texput.pdf

### ISSUE THREAD

**Issue by samlinux** [saadq/node-latex#13]
Hi, I have some "random" problems with the pfd generation.
I get the following error message sometimes and sometimes not.
 
>LaTeX Syntax Error
>! I can't write on file `texput.pdf'.
>! Emergency stop.

The latex document as such is syntactically ok. And under the /tmp directory the log and aux files are created. The error seems totally random ? 
Maybe it depends on the environment? I use a LXC Container with Ubuntu 16.10

I would appreciate any help!

**Comment by saadq** [comment]
Hey @samlinux! Haven't encountered an issue like this personally, but going to try and see if I can help. Could you share an example piece of TeX code you used that caused the error? Also, can you also share a small code snippet of how you're using the `node-latex` module? Thanks!

In the mean time, looking up the error, I found two StackExchange question/answers that may be relevant:

1. https://tex.stackexchange.com/a/78371/78659
2. https://tex.stackexchange.com/a/184599/78659

In both of these, the top answer seems to say that this error happens when the PDF file already exists and you have that PDF open in some PDF reader. Apparently, some PDF readers lock the PDF file and don't allow any changes to it when it is open. Could you just verify this by making sure you don't have the PDF open when running your program to generate the new PDF?

**Comment by samlinux** [comment]
Hi thanks for your quick response.
I use node-latex with an express.js application.

- I create the tex file with a db query
- after that I use handlebars to fill in some data
- and finally the pdf is ready expressjs returns a given download ID with which the client can download the file

In principle I use the wrapper in this way:

>latex(latexDoc,options).on('error', (err) =>{
        let erg = {}
        _.set(erg,'latexError',_.get(err,'message',''))
        return resolve(erg)
      }).pipe(output).on('finish', () => {
          let doc = {
              path:filePath, name:fileName, dlName:dlName
          }
          co(function*(){
            let dlInfo = yield _this.storeDlLink(doc)
            return resolve(dlInfo)
          }).catch((err) => {
            throw new Error(err)
          })
        })

We use an ubuntu 16.x LXD Server to host two LXC Containers with the same application and in both we have exactly the same issues, after a restart of the LXD Server it works as expected!!

During the PDF creation in the /tmp dir a node-latex dir will be created and the texput.log and texput.aux is created as well. I suspect something has to block a process but I do not know what process this can be, maybe if a compile error happens?

**Comment by saadq** [comment]
Hmm, I will try to look into this a bit around next week when I have time, please let me know if you get any more info in the mean time. Also, could you share an example of the LaTeX doc you're using?

**Comment by samlinux** [comment]
hi, on my way I came across another problem. If I try to create more than one single PDFs I got the same error.

It seems that the latex process is blocked and therefore he can not write to the file ??

For a single PDF-File it works on a VPS and on a docker container.

**Comment by saadq** [comment]
Hey @samlinux, I actually ran into this error myself in production a couple of days ago. What I noticed was that this only happened when `xelatex` was used. After investigating a bit, I ran into this issue here: https://tex.stackexchange.com/a/16901/78659. 

It turns out that `xelatex` requires quite a bit of ram. In my VPS which only had 500mb of RAM, I received the same issue you mentioned. I upgraded my VPS to one that 1GB ram instead, and I noticed that it instantly started working. 

Could you verify that you are using `xelatex`? And would you be able to tell me how much RAM you had in your VPS/containers?

**Comment by samlinux** [comment]
Hey,
you are right. The problem originally comes from too little RAM. I raised the RAM from 1 to 2 GB and I can see on the RAM monitor the raise as well. For now it works. I can also confirm that I use the xelatex compiler and a custom TTF font.

**Comment by saadq** [comment]
I'm going to close this as it seems to have been a hardware issue rather than an issue with the module.
