### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ghost** [saadq/node-latex#21]
Hello,
I'm getting this error:
```
events.js:173
      throw er; // Unhandled 'error' event
Error: ENOENT: no such file or directory, open 'C:\Users\username\AppData\Local\Temp\node-latex11943-4516-s5hath.2iall\texput.log'
```

Here is my code:

Latex string is passed as body param.
```js
'use strict';
const latex = require('node-latex');
const fs = require('fs');
const path = require('path');
module.exports = {
  pdf: ({ request, response }) => {
    const output = fs.createWriteStream(path.resolve('public', 'cv.pdf'));
    const options = {
      inputs: [
        path.resolve('assets', 'latex', 'inputs'),
        path.resolve('assets', 'latex', 'images'),
      ],
      fonts: path.resolve('assets', 'latex', 'fonts', 'itcavantgardestd'),
      cmd: 'xetex',
      errorLogs: path.resolve('public')
    };
    const pdf = latex(request.body.latex, options)
    pdf.pipe(output);
    pdf.on('error', error => {
      console.log(error);
    });
    pdf.on('finish', () => console.log(pdf));
    return null;
  }
};
```

Any idea why I'm getting this unhandled error ?

**Comment by saadq** [comment]
The specific error you're getting is a problem with the library. I am trying to read the error log file that is created by LaTeX (named `texput.log` by default) but in some instances it is not created. In other cases (something I recently found out), the generated file name is named something other than `texput.log`.

To help me debug this, could you install the dev version:

```
npm install node-latex@dev
```

And then running the above code again? Your logs should have a line like:

```js
{ files: [...] }
```

This will basically be a list of files that are generated by running LaTeX. Could you show me what files are created for you? Additionally, this error should be fixed because I am no longer trying to read an error log that doesn't exist. 

I will still need to update the code to look for the proper error log file if it was created though, otherwise the user may not be notified of errors in the TeX document. Your logs will help with that.

---

As a sidenote, you can change `fonts: path.resolve('assets', 'latex', 'fonts', 'itcavantgardestd')` to just `fonts: path.resolve('assets', 'latex', 'fonts')`, which would be more useful in case you ever add additional fonts.

**Comment by rpadaki** [comment]
I noticed the same issue when trying to run something like below:
```javascript
fs = require('fs');
latex = require('node-latex');

stream = latex("\documentclass{article}\begin{document}Hello World!\end{document}");
out = fs.createWriteStream("hello.pdf");

stream.pipe(out);
```
After some inspection, it seems what's going on is that for `\documentclass{article}`, the output and auxiliary files are named `article.pdf`, `article.log`, etc., rather than `texput.*`.

At least in the case of `pdflatex` and `xetex`, I think it's worth specifying the argument `-jobname=texput` when spawning the process. Check out my pull request: #28
