### ISSUE TITLE
Support relative paths in options?

### ISSUE THREAD

**Issue by paultopia** [saadq/node-latex#26]
Hi there, 

Would it be terribly difficult to have the options support relative paths?  I'm trying to include a font in a complicated build that involves using a mustache template to generate a tex file and then building it with node-latex, but having to supply an absolute path for the fonts directory in the options is totally blowing up the build process.  If there isn't some complex latex-related reason why this won't work, I'm happy to try to implement it myself if you're interested...

**Comment by paultopia** [comment]
Actually, it looks like it's as easy as wrapping the options.inputs, options.fonts etc. in `path.resolve()` --- I'm going to just fire off a quick PR for this in a minute!

**Comment by paultopia** [comment]
(although, come to think of it, that might blow up with an array of paths.  but with the addition of a quick check to test if string or array that could be fine....)

**Comment by saadq** [comment]
Hey Paul,

I don't think there is a good reason why the `resolve` isn't done on the library side rather than [making the user do it](https://github.com/saadq/node-latex/blob/master/examples/with-cls/index.js#L9). 

I would actually prefer having this done on the library side to make it more ergonomic for people to use... I also agree with your implementation notes, if it is a string, we just `resolve` it or if it is an array we can `map` over each path and `resolve` each one.

My preference would be to create a function above the `joinPaths` function called `resolvePaths` which will take in a string or array as input and then return the resolved paths as described above.

Then it would just be a matter of changing

```js
const inputs = options.inputs || tempPath
```

to

```js
const inputs = options.inputs ? resolvePaths(options.inputs) : tempPath
```

and same thing for the `options.fonts` probably...

Let me know if that sounds good and if you have any questions. I'd be very happy to get a PR for this, but otherwise lmk if you'd rather not do it and I can take care of it.

**Comment by paultopia** [comment]
Yay!  I'm happy to do it (already started as this comment came in, actually).  PR incoming in 3... 2... 1... :-)
